import { z } from "zod"

export const questionnaireSchema = z.object({
  techSectors: z.array(z.string()).min(1, "Please select at least one tech sector"),
  roleTypes: z.array(z.string()).min(1, "Please select at least one role type"),
  workEnvironment: z.array(z.string()).min(1, "Please select at least one work environment"),
  companySize: z.array(z.string()).min(1, "Please select at least one company size"),
  experienceLevel: z.array(z.string()).min(1, "Please select at least one experience level"),
  workSchedule: z.array(z.string()).min(1, "Please select at least one work schedule"),
  benefits: z.array(z.string()).min(1, "Please select at least one benefit priority"),
  technicalSkills: z.array(z.string()).min(1, "Please select at least one technical skill"),
  location: z.array(z.string()).min(1, "Please select at least one location preference"),
  salaryExpectations: z.array(z.string()).min(1, "Please select at least one salary expectation"),
  learningPriorities: z.array(z.string()).min(1, "Please select at least one learning priority"),
  workCulture: z.array(z.string()).min(1, "Please select at least one work culture preference"),
  careerGoals: z.array(z.string()).min(1, "Please select at least one career goal"),
  teamPreferences: z.array(z.string()).min(1, "Please select at least one team preference"),
  projectTypes: z.array(z.string()).min(1, "Please select at least one project type"),
})

export type QuestionnaireData = z.infer<typeof questionnaireSchema>

export const questionnaireOptions = {
  techSectors: [
    "Artificial Intelligence / Machine Learning",
    "Cloud Computing",
    "Cybersecurity",
    "Data Science / Analytics",
    "DevOps / Infrastructure",
    "E-commerce",
    "FinTech",
    "HealthTech",
    "Mobile Development",
    "Web Development",
    "Gaming",
    "IoT (Internet of Things)",
    "Blockchain / Crypto",
    "EdTech",
  ],
  roleTypes: [
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile Developer",
    "DevOps Engineer",
    "Data Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "Security Engineer",
    "QA / Test Engineer",
    "Product Manager",
    "Engineering Manager",
    "Solutions Architect",
    "UI/UX Designer",
  ],
  workEnvironment: ["Fully Remote", "Hybrid (2-3 days in office)", "Mostly In-Office", "Flexible / Your Choice"],
  companySize: [
    "Startup (1-50 employees)",
    "Small (51-200 employees)",
    "Medium (201-1000 employees)",
    "Large (1001-5000 employees)",
    "Enterprise (5000+ employees)",
  ],
  experienceLevel: [
    "Entry Level (0-2 years)",
    "Mid Level (3-5 years)",
    "Senior (6-10 years)",
    "Lead / Principal (10+ years)",
    "Executive / C-Level",
  ],
  workSchedule: ["Standard 9-5", "Flexible Hours", "Compressed Work Week", "Part-Time", "Contract / Freelance"],
  benefits: [
    "Health Insurance",
    "401k / Retirement Plan",
    "Stock Options / Equity",
    "Unlimited PTO",
    "Professional Development Budget",
    "Remote Work Stipend",
    "Gym Membership",
    "Mental Health Support",
    "Parental Leave",
    "Commuter Benefits",
  ],
  technicalSkills: [
    "JavaScript / TypeScript",
    "Python",
    "Java",
    "C# / .NET",
    "Go",
    "Rust",
    "React / Next.js",
    "Vue / Nuxt",
    "Angular",
    "Node.js",
    "Django / Flask",
    "Spring Boot",
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker / Kubernetes",
    "PostgreSQL / MySQL",
    "MongoDB",
    "Redis",
    "GraphQL",
  ],
  location: [
    "United States",
    "Canada",
    "United Kingdom",
    "Europe",
    "Asia Pacific",
    "Latin America",
    "Remote (Anywhere)",
  ],
  salaryExpectations: ["$50k - $75k", "$75k - $100k", "$100k - $150k", "$150k - $200k", "$200k - $300k", "$300k+"],
  learningPriorities: [
    "New Technologies",
    "Leadership Skills",
    "System Design",
    "Domain Expertise",
    "Soft Skills",
    "Certifications",
    "Open Source Contribution",
    "Mentorship",
  ],
  workCulture: [
    "Fast-paced / High-growth",
    "Stable / Established",
    "Innovative / Experimental",
    "Collaborative / Team-oriented",
    "Independent / Autonomous",
    "Mission-driven",
    "Work-life Balance Focused",
    "Competitive / Performance-driven",
  ],
  careerGoals: [
    "Technical Leadership",
    "People Management",
    "Individual Contributor (IC) Track",
    "Entrepreneurship / Startup",
    "Consulting",
    "Product Management",
    "Research / Academia",
    "Work-life Balance",
  ],
  teamPreferences: [
    "Small Team (2-5 people)",
    "Medium Team (6-15 people)",
    "Large Team (15+ people)",
    "Cross-functional Teams",
    "Specialized Teams",
    "Distributed / Remote Teams",
    "Co-located Teams",
  ],
  projectTypes: [
    "Greenfield / New Projects",
    "Legacy System Maintenance",
    "Product Development",
    "Internal Tools",
    "Customer-facing Applications",
    "Infrastructure / Platform",
    "Research & Development",
    "Short-term Projects",
    "Long-term Projects",
  ],
}
